### ISSUE TITLE
Initialization Error for Problems

### ISSUE THREAD

**Issue by ritchieng** [deepmind/learning-to-learn#1]
I've tested the basic `mnist` configuration along with others.

If you run according to your `README`, you would have the following initialization error where there is a mismatch in the number of arguments passed and the number of arguments required.

```
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "train.py", line 71, in main
    with ms.MonitoredSession() as sess:
TypeError: __init__() takes exactly 4 arguments (1 given)
```

**Environment**
- Tensorflow 0.10.0
- CUDA 8.0
- CuDNN 5.1
- Python 2.7
- Ubuntu 16.04

**Update**
I've checked with another environment and it works. So this might be an environment-specific issue.

**Comment by ritchieng** [comment]
This works with the latest head version

**Confirmed Working Environment**
1. [Tensorflow 0.12 head](https://github.com/ritchieng/tensorflow-aws-ami) or 0.11 
2. CUDA 8.0
3. CuDNN 5.1
4. Python 2.7
5. Ubuntu 16.04 or Ubuntu 14

**Comment by sergomezcol** [comment]
Thanks @ritchieng. We have just pushed some changes to make the code fully compatible with TensorFlow 0.12. Unfortunately, the new version doesn't work with TensorFlow 0.11, but you can use the tf-0.11 branch if you need to run the code with that version.
