### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'RNNCell'

### ISSUE THREAD

**Issue by sebastianruder** [deepmind/learning-to-learn#11]
Hey there,

Thanks a lot for open-sourcing the code of this amazing paper! I'm trying to run your code with the latest version of tensorflow (0.12.1), but I'm getting `AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'RNNCell'`. Could you tell me how to fix this? Has `RNNCell` recently been moved somewhere else?

Thanks a lot for your help in advance!

**Comment by normanheckscher** [comment]
Same issue: https://github.com/deepmind/learning-to-learn/issues/10

**Comment by sebastianruder** [comment]
Missed that. Thank you!
