### ISSUE TITLE
Outputting the optimized parameters after or during evaluation

### ISSUE THREAD

**Issue by gridcellcoder** [deepmind/learning-to-learn#4]
What is the best way to determine the optimised/optimizee variables/parameters after a run (or during it)?

`print_stats` only provides loss and epoch time. It would be good to know the current state of the optimizee in this case. 

E.g. for the "simple" problem the current value of x whilst x^2 is being evaluated.

**Comment by sergomezcol** [comment]
The `meta_minimize()` method in the `MetaOptimizer` class returns a `namedtuple` that contains a tensor with the state of the optimizee parameters at the end of an unroll. You can just add that to the call to `sess.run()` and print the results to look at the state of the optimizee.

The `train` function in `convergence_test.py` is a good example of how to do this.
